alter resource group admin_group set CONCURRENCY 10;
alter resource group admin_group set CPU_RATE_LIMIT 10;
alter resource group admin_group set MEMORY_LIMIT 10;
alter resource group admin_group set MEMORY_SHARED_QUOTA 90;
alter resource group admin_group set MEMORY_SPILL_RATIO 90;
alter resource group default_group set CONCURRENCY 5;
alter resource group default_group set CPU_RATE_LIMIT 90;
alter resource group default_group set MEMORY_LIMIT 90;
alter resource group default_group set MEMORY_SHARED_QUOTA 90;
alter resource group default_group set MEMORY_SPILL_RATIO 20;
SELECT * FROM gp_toolkit.gp_resgroup_config;
